### ISSUE TITLE
Algorithm Efficiency

### ISSUE THREAD

**Issue by joebiker** [Aldebaron/HW2#6]
How do you reduce computer cycles? Each line of code takes a finite amount of time. Each pass through a loop takes time. Can you reduce the amount of time in any way? 

Why do this? If you are building an algorithm, you want it to finish in a reasonable amount of time. Or if a user requests information, we don't want to make them wait too long to retrieve it.  Google has spent it's entire eco system around parsing your search results quickly for the best experience.

What if there are 100,000 messages?
Other considerations?

## MessagingService

Create a bunch of messages, like 1,000! 10k? 100k?  Check how the various methods or loops perform.

1) Create a for loop around the existing Add()
1) How many is enough? Start with 1,000 iterations of the loop (roughly 12,000 message will be generated). 
1) How long did that take? 

## Microsoft Stopwatch
Add this code to the above loop (before and after). Write the output to console.log

```
// Start timing.
Stopwatch stopwatch = new Stopwatch();
stopwatch.Start();

// Stop timing.
stopwatch.Stop();
var stopwatchresult = String.Format("That took {0} milliseconds!", stopwatch.ElapsedMilliseconds);
Console.WriteLine(stopwatchresult);
```

## Final Homework

Now play with the ReadMessage and Inbox functions. what's the most efficient way to retrieve a message?
Create a spreadsheet and track different code designs and how long it takes to get a message. 

We may look into Unit Testing as a source to test / time this.

**Comment by Aldebaron** [comment]
I came up with new code for the inbox function, which is on average 73 milliseconds faster than the old code. It's also just way less complicated.

I spent quite a bit of time staring at it, but I'm not sure how to refine ReadMessage to be any faster. I don't have much practice with this kind of editing, so I don't have many ideas, and I already implemented the few that I had. Also, it takes 0-1 milliseconds to read messages between Steve and Al, so it's not a huge one, either.
